In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [3]:
df = pd.read_csv('pokemon_alopez247.csv')

In [4]:
df

Number        Name   Type_1  Type_2  Total   HP  Attack  Defense  Sp_Atk  \
0         1   Bulbasaur    Grass  Poison    318   45      49       49      65   
1         2     Ivysaur    Grass  Poison    405   60      62       63      80   
2         3    Venusaur    Grass  Poison    525   80      82       83     100   
3         4  Charmander     Fire     NaN    309   39      52       43      60   
4         5  Charmeleon     Fire     NaN    405   58      64       58      80   
..      ...         ...      ...     ...    ...  ...     ...      ...     ...   
716     717     Yveltal     Dark  Flying    680  126     131       95     131   
717     718     Zygarde   Dragon  Ground    600  108     100      121      81   
718     719     Diancie     Rock   Fairy    600   50     100      150     100   
719     720       Hoopa  Psychic   Ghost    600   80     110       60     150   
720     721   Volcanion     Fire   Water    600   80     110      120     130   

     Sp_Def  ...   Color  hasGender  Pr_Male   Egg_Group_1  Egg_Group_2  \
0        65  ...   Green       True    0.875       Monster        Grass   
1        80  ...   Green       True    0.875       Monster        Grass   
2       100  ...   Green       True    0.875       Monster        Grass   
3        50  ...     Red       True    0.875       Monster       Dragon   
4        65  ...     Red       True    0.875       Monster       Dragon   
..      ...  ...     ...        ...      ...           ...          ...   
716      98  ...     Red      False      NaN  Undiscovered          NaN   
717      95  ...   Green      False      NaN  Undiscovered          NaN   
718     150  ...    Pink      False      NaN  Undiscovered          NaN   
719     130  ...  Purple      False      NaN  Undiscovered          NaN   
720      90  ...   Brown      False      NaN  Undiscovered          NaN   

     hasMegaEvolution Height_m Weight_kg  Catch_Rate       Body_Style  
0               False     0.71       6.9          45        quadruped  
1               False     0.99      13.0          45        quadruped  
2                True     2.01     100.0          45        quadruped  
3               False     0.61       8.5          45   bipedal_tailed  
4               False     1.09      19.0          45   bipedal_tailed  
..                ...      ...       ...         ...              ...  
716             False     5.79     203.0          45        two_wings  
717             False     5.00     305.0           3  serpentine_body  
718              True     0.71       8.8           3        head_arms  
719             False     0.51       9.0           3        head_only  
720             False     1.70     195.0           3        quadruped  

[721 rows x 23 columns]

In [5]:
df = df[['isLegendary','Generation', 'Type_1', 'Type_2', 'HP', 'Attack', 'Defense', 'Sp_Atk', 'Sp_Def', 'Speed','Color','Egg_Group_1','Height_m','Weight_kg','Body_Style']]

In [6]:
df['isLegendary'] = df['isLegendary'].astype(int)

C:\Users\RENANL~1\AppData\Local\Temp/ipykernel_12592/2158926395.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isLegendary'] = df['isLegendary'].astype(int)


In [7]:
def dummy_creation(df, dummy_creation):
    for i in dummy_creation:
        df_dummy = pd.get_dummies(df[i])
        df = pd.concat([df,df_dummy],axis=1)
        df = df.drop(i, axis=1)
    return(df)

In [8]:
df = dummy_creation(df, ['Egg_Group_1', 'Body_Style', 'Color','Type_1', 'Type_2'])

In [9]:
df

isLegendary  Generation   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  \
0              0           1   45      49       49      65      65     45   
1              0           1   60      62       63      80      80     60   
2              0           1   80      82       83     100     100     80   
3              0           1   39      52       43      60      50     65   
4              0           1   58      64       58      80      65     80   
..           ...         ...  ...     ...      ...     ...     ...    ...   
716            1           6  126     131       95     131      98     99   
717            1           6  108     100      121      81      95     95   
718            1           6   50     100      150     100     150     50   
719            1           6   80     110       60     150     130     70   
720            1           6   80     110      120     130      90     70   

     Height_m  Weight_kg  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0        0.71        6.9  ...      0      0       0    0       0       1   
1        0.99       13.0  ...      0      0       0    0       0       1   
2        2.01      100.0  ...      0      0       0    0       0       1   
3        0.61        8.5  ...      0      0       0    0       0       0   
4        1.09       19.0  ...      0      0       0    0       0       0   
..        ...        ...  ...    ...    ...     ...  ...     ...     ...   
716      5.79      203.0  ...      0      0       0    0       0       0   
717      5.00      305.0  ...      0      0       1    0       0       0   
718      0.71        8.8  ...      0      0       0    0       0       0   
719      0.51        9.0  ...      1      0       0    0       0       0   
720      1.70      195.0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
0          0     0      0      0  
1          0     0      0      0  
2          0     0      0      0  
3          0     0      0      0  
4          0     0      0      0  
..       ...   ...    ...    ...  
716        0     0      0      0  
717        0     0      0      0  
718        0     0      0      0  
719        0     0      0      0  
720        0     0      0      1  

[721 rows x 85 columns]

In [13]:
def train_test_splitter(DataFrame, colunm):
    df_train = DataFrame.loc[df[colunm] != 1]
    df_test = DataFrame.loc[df[colunm] == 1]

    df_train = df_train.drop(colunm, axis=1)
    df_test = df_test.drop(colunm, axis=1)

    return(df_train, df_test)
    #Função que divide o data frame em dois de teste e de traino da geração  Red Blue e da Yellow serão nosso teste e a 
    # e as demais geração serão as de treino # 

df_train, df_test = train_test_splitter(df,'Generation')

In [14]:
df_train.head()

isLegendary  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
151            0  45      49       65      49      65     45      0.89   
152            0  60      62       80      63      80     60      1.19   
153            0  80      82      100      83     100     80      1.80   
154            0  39      52       43      60      50     65      0.51   
155            0  58      64       58      80      65     80      0.89   

     Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
151        6.4          0  ...      0      0       0    0       0       0   
152       15.8          0  ...      0      0       0    0       0       0   
153      100.5          0  ...      0      0       0    0       0       0   
154        7.9          0  ...      0      0       0    0       0       0   
155       19.0          0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
151        0     0      0      0  
152        0     0      0      0  
153        0     0      0      0  
154        0     0      0      0  
155        0     0      0      0  

[5 rows x 84 columns]

In [15]:
df_test.head()

isLegendary  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
0            0  45      49       49      65      65     45      0.71   
1            0  60      62       63      80      80     60      0.99   
2            0  80      82       83     100     100     80      2.01   
3            0  39      52       43      60      50     65      0.61   
4            0  58      64       58      80      65     80      1.09   

   Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0        6.9          0  ...      0      0       0    0       0       1   
1       13.0          0  ...      0      0       0    0       0       1   
2      100.0          0  ...      0      0       0    0       0       1   
3        8.5          0  ...      0      0       0    0       0       0   
4       19.0          0  ...      0      0       0    0       0       0   

   Psychic  Rock  Steel  Water  
0        0     0      0      0  
1        0     0      0      0  
2        0     0      0      0  
3        0     0      0      0  
4        0     0      0      0  

[5 rows x 84 columns]

In [36]:
def label_delineator(df_train, df_test, label):
    train_data = df_train.drop(label,axis=1).values ##
    train_labels = df_train[label].values
    test_data = df_test.drop(label, axis=1).values
    test_labels = df_test[label].values
    # Essa função separa os rotulos como no nosso caso usaremos isLegendary 
    # Ele separa os dados em forma de matriz que é o valor que nosso algoritmo entende #

    return(train_data, train_labels, test_data, test_labels)


In [37]:
train_data, train_labels, test_data, test_labels = label_delineator(df_train, df_test, 'isLegendary')


In [38]:
print(train_data)

[[ 45.  49.  65. ...   0.   0.   0.]
 [ 60.  62.  80. ...   0.   0.   0.]
 [ 80.  82. 100. ...   0.   0.   0.]
 ...
 [ 50. 100. 150. ...   0.   0.   0.]
 [ 80. 110.  60. ...   0.   0.   0.]
 [ 80. 110. 120. ...   0.   0.   1.]]


In [39]:
print(train_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 1 1 1 1 1 

In [40]:
print(train_data)

[[ 45.  49.  65. ...   0.   0.   0.]
 [ 60.  62.  80. ...   0.   0.   0.]
 [ 80.  82. 100. ...   0.   0.   0.]
 ...
 [ 50. 100. 150. ...   0.   0.   0.]
 [ 80. 110.  60. ...   0.   0.   0.]
 [ 80. 110. 120. ...   0.   0.   1.]]


In [41]:
print(test_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0
 0 1 0]


In [42]:
def data_normalizer(train_data, test_data):
    train_data = preprocessing.MinMaxScaler().fit_transform(train_data)
    test_data = preprocessing.MinMaxScaler().fit_transform(test_data)
    # Função que normaliza os dados e transforma e deixa eles na mesma escala #

    return(train_data, test_data)


In [43]:
train_data, test_data = data_normalizer(train_data, test_data)

In [44]:
print(train_data)

[[0.17322835 0.275      0.26666667 ... 0.         0.         0.        ]
 [0.23228346 0.35625    0.33333333 ... 0.         0.         0.        ]
 [0.31102362 0.48125    0.42222222 ... 0.         0.         0.        ]
 ...
 [0.19291339 0.59375    0.64444444 ... 0.         0.         0.        ]
 [0.31102362 0.65625    0.24444444 ... 0.         0.         0.        ]
 [0.31102362 0.65625    0.51111111 ... 0.         0.         1.        ]]


In [46]:
print(test_data)

[[0.14583333 0.34108527 0.25142857 ... 0.         0.         0.        ]
 [0.20833333 0.44186047 0.33142857 ... 0.         0.         0.        ]
 [0.29166667 0.59689922 0.44571429 ... 0.         0.         0.        ]
 ...
 [0.3375     1.         0.51428571 ... 0.         0.         0.        ]
 [0.4        0.81395349 0.48571429 ... 0.         0.         0.        ]
 [0.375      0.73643411 0.54285714 ... 0.         0.         0.        ]]


In [47]:
# Keras é um API para o tensorflow 
# um modelo é contruido sobre camadas nesse modelo vamos fazer duas camadas neurais  conectadas 
# o numero de camadas associados a eles serão o numero de camadas.
# Na primeira camada vai ser usado a função 'ReLU' (Rectified Linear Unit) e na primeira camada precisamos especificar nosso input_size
# a forma de entrada em nosso conjunto de dados
# Depois  é feito uma outra camada softmax que é um tipo de regressão logica feita para situações de multiplos casos
# Como no nosso caso é Lendario e não Lendario , com isso delinearemos as possiveis indentidades do pokémon em dois grupos de possibilidades#

In [49]:
length = train_data.shape[1]

model = keras.Sequential()
model.add(keras.layers.Dense(500, activation='relu', input_shape=[length,]))
model.add(keras.layers.Dense(2, activation='softmax'))

In [50]:
print(model)

In [57]:
print(length)

83
